from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from app.agents.graph import app_graph
from app.api.endpoints.auth import oauth2_scheme  # Reverting to our established Zero-Trust perimeter
from langchain_core.messages import HumanMessage

router = APIRouter()

class ChatInput(BaseModel):
    message: str

class ChatResponse(BaseModel):
    response: str

@router.post("/invoke", response_model=ChatResponse)
async def invoke_orchestration_engine(
    payload: ChatInput,
    token: str = Depends(oauth2_scheme)  # Use the validated JWT as the gatekeeper
):
    try:
        # We use the actual secure JWT string as the unique thread session key.
        # This perfectly isolates memory per active executive session without needing database lookups.
        config = {"configurable": {"thread_id": token}}
        
        # Format the incoming text as a LangChain structure
        initial_state = {"messages": [HumanMessage(content=payload.message)]}
        
        # Execute the LangGraph cycle with memory persistence
        output_state = app_graph.invoke(initial_state, config=config)
        
        # Extract the final response generated by the Groq-powered core
        final_message = output_state["messages"][-1]
        
        return ChatResponse(response=final_message.content)
        
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Orchestration Engine Execution Failure: {str(e)}"
        )